Repository patrickpr/trapdirector, pull requests merged in 2020-05, with the labels that each got.

#33 Install doc edits
  docs/01-install.md
Labels: doc

#34 Installation fixes
  application/controllers/SettingsController.php
  bin/installer.sh
Labels: enhancement

#35 only try /usr/sbin/ss if ss can not be found in the search path
  application/controllers/SettingsController.php
Labels: bug
